version: '3.8'

services:
  crmercury-worker:
    build: .
    container_name: crmercury-worker-node
    restart: always
    environment:
      - NODE_ENV=production
      - MERCURY_LICENSE_KEY=${MERCURY_LICENSE_KEY}
      - MERCURY_API_URL=${MERCURY_API_URL:-https://crm.mercuryhub.com.ar/api}
      - PORT=10000
    volumes:
      - ./.baileys_auth:/app/.baileys_auth
    ports:
      - "10000:10000"

volumes:
  baileys_auth_data:
